### ISSUE TITLE
StreamDebugger.h: No such file or directory

### ISSUE THREAD

**Issue by royalcheese71** [vshymanskyy/StreamDebugger#1]
Hi, 

First of all Thanks for your work! 

I experienced a problem with the library taken from arduino Lib tool : 
`Diagnostics:50:28: error: StreamDebugger.h: No such file or directory
compilation terminated.
exit status 1`

Maybe a failing with the arduino library update or uploading ? 
I'm on it, but if you may have some solution

THank a lot, have a nice day !

**Comment by slovekkania** [comment]
Hi
just add StreamDebugger in Arduino's Library Manager
